apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-production-e2e-deployment
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: krishnamsg/complete-prodcution-e2e-pipeline
        name: guestbook-ui
        ports:
        - containerPort: 80
