apiVersion: v1
kind: Service
metadata:
  name: complete-production-e2e-app
spec:
  selector:
    app: complete-prodcution-e2e-pipeline
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort  # Adjust the service type as needed
