apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-production-e2e-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: complete-production-e2e-app
  template:
    metadata:
      labels:
        app: complete-production-e2e-app
    spec:
      containers:
      - name: complete-prodcution-e2e-app
        image: krishnamsg/complete-prodcution-e2e-pipeline:1.0.0-30
        ports:
        - containerPort: 8080
